source 'https://github.com/CocoaPods/Specs.git'

target 'sails.ios', :exclusive => true do
  pod "sails.ios", :path => "../sails.ios.podspec"
end

target 'Tests', :exclusive => true do
  pod "sails.ios", :path => "../sails.ios.podspec"

  pod 'Specta', '~> 0.2.1'
  pod 'Expecta'
  pod 'OHHTTPStubs', '~> 3.1.7'
end
